// Auto-generated by VibeStack — do not edit manually

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          user_id: string;
          display_name: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          display_name: string | null;
          avatar_url: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      wards: {
        Row: {
          id: string;
          name: string;
          floor: string | null;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          floor: string | null;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          floor?: string | null;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      assignments: {
        Row: {
          id: string;
          user_id: string;
          assignment_role: string;
          profile_id: string;
          ward_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          assignment_role: string;
          profile_id: string;
          ward_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          assignment_role?: string;
          profile_id?: string;
          ward_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      patients: {
        Row: {
          id: string;
          mrn: string;
          full_name: string;
          dob: string | null;
          primary_physician_id: string | null;
          ward_id: string;
          bed_id: string;
          profile_id: string;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          mrn: string;
          full_name: string;
          dob: string | null;
          primary_physician_id: string | null;
          ward_id: string;
          bed_id: string;
          profile_id: string;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          mrn?: string;
          full_name?: string;
          dob?: string | null;
          primary_physician_id?: string | null;
          ward_id?: string;
          bed_id?: string;
          profile_id?: string;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      clinical_notes: {
        Row: {
          id: string;
          author_id: string;
          note: string;
          patient_id: string;
          profile_id: string;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          author_id: string;
          note: string;
          patient_id: string;
          profile_id: string;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          author_id?: string;
          note?: string;
          patient_id?: string;
          profile_id?: string;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          content: string;
          channel_id: string;
          user_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          content: string;
          channel_id?: string;
          user_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          content?: string;
          channel_id?: string;
          user_id?: string;
          created_at?: string;
        };
      };
      beds: {
        Row: {
          id: string;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Enums: {
    };
  };
};